services:
  - type: web
    name: lead-management-system
    env: python
    plan: free
    buildCommand: pip install -r render-requirements.txt
    # No post-deploy command to create admin - we'll use the setup route instead
    startCommand: gunicorn main:app --bind 0.0.0.0:5000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lead-management-db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: SETUP_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: true
    # Show a helpful message after deployment with the setup URL
    healthCheckPath: /
    domains:
      - nextus.onrender.com

databases:
  - name: lead-management-db
    plan: free
    databaseName: leaddb
    user: leaduser
